# Generated by Django 3.0.6 on 2020-06-18 18:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=200)),
                ('completed', models.BooleanField(default=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
